spring.application.name=springrest
server.port=4422
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=course
#spring.data.mongodb.username=
#spring.data.mongodb.password=

